## Misc
- 错误应该传递给更清楚程序整个状态的协程(比如`main`)，以便正确的处理
- 协程可以使用包含`error`属性的数据结构，传递错误给调用者协程
```
//包含Error属性的返回结果
type Result struct {
	Error error
	Value int
}

func intStream(done <-chan int)(<-chan Result){
	resultStream:=make(chan Result)

	go func() {
		defer close(resultStream)

		for{
			result:=Result{
				Value:rand.Intn(100),
			}
            
            //设置错误对象给Error属性
			if result.Value%2!=0{
				result.Error= fmt.Errorf("Odd Num: %v", result.Value)
			}

			select {
			case <-done:
				return
			case resultStream<-result:
			}
		}
	}()

	return resultStream
}

func main() {
	done:=make(chan int)
	defer close(done)
    
    //把错误对象传递给main协程处理
	stream:=intStream(done)
	for result:=range stream{
		if(result.Error!=nil){
			fmt.Printf("Error: %v",result.Error)
			break
		}

		fmt.Println(result.Value)
	}

}
```